---
- hosts: 192.168.56.111
  become: true
  tasks:

  - name: httpd package installation
    dnf: 
     name: httpd
     state: present
     update_cache: yes

  - name: starting httpd service
    service:
     name: httpd
     state: started
     enabled: yes

